import numpy as np 
array_1d = np.array([1, 2, 3, 4, 5])
print("Одномерный массив:", array_1d)
array_1d2 = np.array([[1,2,3],[4,5,6]])
print("Двухмерный массив:", array_1d2)
array_float = np.array([1,2,3],dtype=float)
array_zeros = np.zeros((1,3))
print(array_zeros)
array_ones = np.ones((1,2))
print(array_ones)
array_range_1 = np.arange(10)
print(array_range_1)
